name: ecommerce25_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.1.0
  carousel_slider: ^5.0.0
  bloc: ^9.0.0
  flutter_bloc: ^9.1.0
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  badges: ^3.1.2
  animated_text_kit: ^4.2.3
  flutter_screenutil: ^5.9.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  json_serializable: ^6.9.5
  freezed: ^3.0.6

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/fruit/
    - assets/images/checkout/
    - assets/images/pay/
    - assets/images/confirm_order/

  fonts:
   - family: Prime
     fonts:
       - asset: assets/fonts/Prime-Light.otf
         weight: 300
       - asset: assets/fonts/Prime-Regular.otf
         weight: 400
   - family: Inter
     fonts:
       - asset: assets/fonts/Inter_18pt-Regular.ttf
         weight: 400
       - asset: assets/fonts/Inter_18pt-Bold.ttf
         weight: 700

   - family: Roboto
     fonts:
       - asset: assets/fonts/Roboto_Condensed-Regular.ttf
         weight: 400
       - asset: assets/fonts/Roboto_Condensed-Bold.ttf
         weight: 700

   - family: Helvetica
     fonts:
       - asset: assets/fonts/Helvetica.ttf

   - family: BalooDa
     fonts:
       - asset: assets/fonts/BalooDa-Regular.ttf



